
--更多页面布局

local MaterialCardView = luajava.bindClass "com.google.android.material.card.MaterialCardView"
local AppCompatTextView = luajava.bindClass "androidx.appcompat.widget.AppCompatTextView"
local AppCompatImageView = luajava.bindClass "androidx.appcompat.widget.AppCompatImageView"
local NestedScrollView = luajava.bindClass "androidx.core.widget.NestedScrollView"
local LinearLayoutCompat = luajava.bindClass "androidx.appcompat.widget.LinearLayoutCompat"
local Space = luajava.bindClass "android.widget.Space"


return {
  NestedScrollView,
  layout_width=-1,
  layout_height=-1,
  fillViewport=true,
  {
    LinearLayoutCompat,
    layout_width=-1,
    layout_height=-1,
    orientation=1,--1垂直，0水平
    {
      MaterialCardView,
      layout_margin="16dp",
      layout_width=-1,
      layout_height=-2,
      cardBackgroundColor=Colors.colorSurfaceVariant,
      {
        LinearLayoutCompat,
        layout_width=-1,
        layout_height=-1,
        orientation=0,
        id="infoCardMore",
        onClick=function() end,
        {
          MaterialCardView,
          layout_gravity="center",
          layout_margin="16dp",
          layout_marginLeft="32dp",
          {
            AppCompatImageView,
            src="icon.png",
            layout_gravity="center",
            layout_width="130dp",
            layout_height="130dp",
            id="iconMore",
            onClick=function() end,
          },
        },
        {
          LinearLayoutCompat,
          orientation=1,
          layout_height=-1,
          layout_width=-1,
          gravity="center",
          layout_marginRight="16dp",
          {
            AppCompatTextView,
            text="MikuBeat",
            textSize="24sp",
            layout_marginTop="16dp",
            layout_marginBottom="16dp",
            layout_marginBottom=0,
            maxLines=1,
            textColor=Colors.colorOnBackground
          },
          {
            AppCompatTextView,
            text=activity.getPackageManager().getPackageInfo(activity.getPackageName(), 0).versionName,
            textSize="16sp",
            layout_marginTop="6dp",
            layout_marginBottom="6dp",
            id="versionNameMore",
            maxLines=1,
            onClick=function()
              local update = require "update"
              update.checkUpdate()
            end,
          },
        },
      },
    },
    {
      MaterialCardView,
      layout_width=-1,
      layout_height=-2,
      strokeWidth="0dp",
      layout_margin="16dp",
      layout_marginBottom="0dp",
      cardBackgroundColor=Colors.colorSurfaceContainer,--colorSurfaceVariant
      {
        LinearLayoutCompat,
        layout_width=-1,
        orientation=0,
        id="checkUpdateMore",
        onClick=function()
          local update = require "update"
          update.checkUpdate()
        end,
        {
          AppCompatImageView,
          colorFilter=Colors.colorOnSurfaceVariant,
          src="res/imgs/update.png",
          layout_height="30dp",
          layout_width="30dp",
          padding="3dp",
          layout_gravity="center|left",
          layout_margin="16dp",
        },
        {
          AppCompatTextView,
          text="检测更新",
          layout_weight=1,
          layout_gravity="center|left",
          textSize="16sp",
          textColor=Colors.colorOnBackground,
        },
        {
          AppCompatImageView,
          colorFilter=Colors.colorOnSurfaceVariant,
          layout_height="20dp",
          layout_width="20dp",
          layout_gravity="center|right",
          src="res/imgs/go.png",
          layout_margin="16dp",
        },
      },
    },
    {
      MaterialCardView,
      layout_width=-1,
      layout_height=-2,
      strokeWidth="0dp",
      layout_margin="16dp",
      layout_marginBottom="0dp",
      cardBackgroundColor=Colors.colorSurfaceContainer,--colorSurfaceVariant
      {
        LinearLayoutCompat,
        layout_width=-1,
        orientation=0,
        id="joinUsMore",
        onClick=function()
          local Uri = luajava.bindClass "android.net.Uri"
          local Intent = luajava.bindClass "android.content.Intent"
          xpcall(function()
            activity.startActivity(Intent(Intent.ACTION_VIEW, Uri.parse("mqqapi://card/show_pslcard?src_type=internal&version=1&uin=912150197&card_type=group&source=qrcode")))
            end, function()
            copyText("912150197")
            local myToast = require "myToast"
            myToast.toast("跳转QQ异常，已复制群号")
          end)
        end,
        {
          AppCompatImageView,
          colorFilter=Colors.colorOnSurfaceVariant,
          src="res/imgs/QQ.png",
          layout_height="30dp",
          layout_width="30dp",
          padding="3dp",
          layout_gravity="center|left",
          layout_margin="16dp",
        },
        {
          AppCompatTextView,
          text="加入交流群",
          layout_weight=1,
          layout_gravity="center|left",
          textSize="16sp",
          textColor=Colors.colorOnBackground,
        },
        {
          AppCompatImageView,
          colorFilter=Colors.colorOnSurfaceVariant,
          layout_height="20dp",
          layout_width="20dp",
          layout_gravity="center|right",
          src="res/imgs/go.png",
          layout_margin="16dp",
        },
      },
    },
    {
      MaterialCardView,
      layout_width=-1,
      layout_height=-2,
      strokeWidth="0dp",
      layout_margin="16dp",
      layout_marginBottom="0dp",
      cardBackgroundColor=Colors.colorSurfaceContainer,--colorSurfaceVariant
      {
        LinearLayoutCompat,
        layout_width=-1,
        orientation=0,
        id="about",
        {
          AppCompatImageView,
          colorFilter=Colors.colorOnSurfaceVariant,
          src="res/imgs/about.png",
          layout_height="30dp",
          layout_width="30dp",
          padding="4dp",
          layout_gravity="center|left",
          layout_margin="16dp",
        },
        {
          AppCompatTextView,
          text="关于",
          layout_weight=1,
          layout_gravity="center|left",
          textSize="16sp",
          textColor=Colors.colorOnBackground,
        },
        {
          AppCompatImageView,
          colorFilter=Colors.colorOnSurfaceVariant,
          layout_height="20dp",
          layout_width="20dp",
          layout_gravity="center|right",
          src="res/imgs/go.png",
          layout_margin="16dp",
        },
      },
    },
    {
      MaterialCardView,
      layout_width=-1,
      layout_height=-2,
      strokeWidth="0dp",
      layout_margin="16dp",
      layout_marginBottom="0dp",
      cardBackgroundColor=Colors.colorSurfaceContainer,--colorSurfaceVariant
      {
        LinearLayoutCompat,
        layout_width=-1,
        orientation=0,
        id="setting",
        {
          AppCompatImageView,
          colorFilter=Colors.colorOnSurfaceVariant,
          src="res/imgs/setting.png",
          layout_height="30dp",
          layout_width="30dp",
          padding="4dp",
          layout_gravity="center|left",
          layout_margin="16dp",
        },
        {
          AppCompatTextView,
          text="设置",
          layout_weight=1,
          layout_gravity="center|left",
          textSize="16sp",
          textColor=Colors.colorOnBackground,
        },
        {
          AppCompatImageView,
          colorFilter=Colors.colorOnSurfaceVariant,
          layout_height="20dp",
          layout_width="20dp",
          layout_gravity="center|right",
          src="res/imgs/go.png",
          layout_margin="16dp",
        },
      },
    },
    {
      Space,
      layout_width=-1,
      layout_height="170dp",
    },
  },
}

